apiVersion: v1
kind: Service
metadata:
  name: dev-deployment-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: development-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

